### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by gofur** [mintware-de/flutter_barcode_reader#105]
Hi Anyone,
i found bug on barcode scan, my flutter version 1.0.0
anyone can help me?

Fatal Exception: java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics
       at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt)
       at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(BarcodeScanPlugin.kt)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:34)
       at com.kompasgramedia.myvalue.MainActivity.onCreate(MainActivity.java:60)
       at android.app.Activity.performCreate(Activity.java:5122)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
       at android.app.ActivityThread.access$600(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5370)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by guyzk** [comment]
Same issue here

**Comment by devtronic** [comment]
Please try the latest release.
