### ISSUE TITLE
Unable to scan barcode 

### ISSUE THREAD

**Issue by prabhuk56** [mintware-de/flutter_barcode_reader#258]
When i try to scan barcode, it is displaying white blank screen and it is throwing following exception.

-------
2020-06-19 14:46:43.963 22592-22592/com.thirantech.inventory W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2020-06-19 14:46:43.965 22592-22592/com.thirantech.inventory W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2020-06-19 14:46:43.967 22592-22592/com.thirantech.inventory W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2020-06-19 14:46:45.022 22592-22592/com.thirantech.inventory V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@ac7920d[]
2020-06-19 14:46:45.022 22592-23069/com.thirantech.inventory E/SystemUtil: /data/system/sim.properties doesn't exist,try to create it,some methods of this class will throw exception if create the file failed
2020-06-19 14:46:45.022 22592-23069/com.thirantech.inventory W/System.err: java.io.IOException: Permission denied
2020-06-19 14:46:45.024 22592-22592/com.thirantech.inventory D/WindowClient: Add to mViews: DecorView@ac7920d[BarcodeScannerActivity], this = android.view.WindowManagerGlobal@ffd9976
2020-06-19 14:46:45.024 22592-23069/com.thirantech.inventory W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-06-19 14:46:45.024 22592-23069/com.thirantech.inventory W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2020-06-19 14:46:45.024 22592-23069/com.thirantech.inventory W/System.err:     at java.io.File.createNewFile(File.java:1000)
2020-06-19 14:46:45.024 22592-23069/com.thirantech.inventory W/System.err:     at android.util.SystemUtil.<clinit>(SystemUtil.java:54)
2020-06-19 14:46:45.024 22592-23069/com.thirantech.inventory W/System.err:     at android.util.SystemUtil.writeCameraState(Unknown Source:0)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at android.hardware.Camera.open(Camera.java:407)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at me.dm7.barcodescanner.core.CameraUtils.getCameraInstance(CameraUtils.java:35)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at me.dm7.barcodescanner.core.CameraHandlerThread$1.run(CameraHandlerThread.java:26)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Looper.loop(Looper.java:164)
2020-06-19 14:46:45.025 22592-23069/com.thirantech.inventory W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err: java.io.IOException: No such file or directory
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at java.io.File.createNewFile(File.java:1000)
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at android.util.SystemUtil.writeCameraState(SystemUtil.java:204)
2020-06-19 14:46:45.026 22592-22592/com.thirantech.inventory D/ViewRootImpl[BarcodeScannerActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at android.hardware.Camera.open(Camera.java:407)
2020-06-19 14:46:45.026 22592-23069/com.thirantech.inventory W/System.err:     at me.dm7.barcodescanner.core.CameraUtils.getCameraInstance(CameraUtils.java:35)
2020-06-19 14:46:45.027 22592-23069/com.thirantech.inventory W/System.err:     at me.dm7.barcodescanner.core.CameraHandlerThread$1.run(CameraHandlerThread.java:26)
2020-06-19 14:46:45.027 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2020-06-19 14:46:45.027 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-06-19 14:46:45.027 22592-23069/com.thirantech.inventory W/System.err:     at android.os.Looper.loop(Looper.java:164)
2020-06-19 14:46:45.027 22592-23069/com.thirantech.inventory W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-06-19 14:46:45.028 22592-23069/com.thirantech.inventory E/SystemUtil: [sendCameraState]flashlightState=0,j=0
2020-06-19 14:46:45.031 22592-22592/com.thirantech.inventory V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{9790c0e com.thirantech.inventory/com.apptreesoftware.barcodescan.BarcodeScannerActivity,ident = 1}, this = DecorView@ac7920d[BarcodeScannerActivity]
2020-06-19 14:46:45.059 22592-22592/com.thirantech.inventory D/Surface: Surface::allocateBuffers(this=0x744f762000)
2020-06-19 14:46:45.059 22592-22660/com.thirantech.inventory D/Surface: Surface::connect(this=0x744f762000,api=1)
2020-06-19 14:46:45.067 22592-22660/com.thirantech.inventory D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
2020-06-19 14:46:45.128 22592-23069/com.thirantech.inventory E/SystemUtil: [sendCameraState]scannerState=0,j=0
2020-06-19 14:46:45.150 22592-22660/com.thirantech.inventory D/HWUIExtension: MTKProgramCache.generateProgram: 240518168576
2020-06-19 14:46:45.151 22592-22660/com.thirantech.inventory D/HWUIExtension: createProgram 0x0000003800000000, binary 0x74f70823fc, length 4812, format 36705 within 858ns
2020-06-19 14:46:45.152 22592-22660/com.thirantech.inventory D/HWUIExtension: MTKProgramCache.generateProgram: 562984313159683
2020-06-19 14:46:45.152 22592-22660/com.thirantech.inventory D/HWUIExtension: createProgram 0x0002000800000003, binary 0x74f70883ac, length 5140, format 36705 within 327ns
2020-06-19 14:46:45.205 22592-22617/com.thirantech.inventory D/Surface: Surface::disconnect(this=0x7458627000,api=1)
2020-06-19 14:46:45.207 22592-22592/com.thirantech.inventory D/Surface: Surface::disconnect(this=0x7458627000,api=-1)
2020-06-19 14:46:45.210 22592-22660/com.thirantech.inventory D/Surface: Surface::disconnect(this=0x7458622000,api=1)
2020-06-19 14:46:45.229 22592-23069/com.thirantech.inventory E/SystemUtil: sendCameraState PackageName=com.thirantech.inventory
2020-06-19 14:46:45.231 22592-23069/com.thirantech.inventory W/libc: Unable to set property "persist.sys.rscja.camera" to "1": error code: 0x18
2020-06-19 14:46:45.533 22592-22592/com.thirantech.inventory V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = ViewRoot{b007b77 com.thirantech.inventory/com.thirantech.inventory.MainActivity,ident = 0}, this = DecorView@1aa8411[MainActivity]
2020-06-19 14:46:50.836 22592-22592/com.thirantech.inventory V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{b007b77 com.thirantech.inventory/com.thirantech.inventory.MainActivity,ident = 0}, this = DecorView@1aa8411[MainActivity]
2020-06-19 14:46:50.861 22592-22660/com.thirantech.inventory D/Surface: Surface::connect(this=0x7458622000,api=1)
2020-06-19 14:46:50.863 22592-22660/com.thirantech.inventory D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000

----------

**Comment by devtronic** [comment]
Please use the bug report issue template.
