### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by saif97** [mintware-de/flutter_barcode_reader#272]
**Describe the bug**
Exception when compiling a project after upgrading to flutter 1.20 stable. The project works when the package is removed. 

**To Reproduce**
I've tried to reproduce using the example provided and by creating a new project but it worked just fine. 
**Logs**
```
[   +2 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Some problems were found with the configuration of task ':barcode_scan:generateDebugProto'.
[   +1 ms] > Directory 'L:\Flutter\Projects\<projectName>\build\barcode_scan\extracted-protos\debug' specified for property '$6' does not exist.
[        ] > Directory 'L:\Flutter\Projects\<projectName>\build\barcode_scan\extracted-protos\main' specified for property '$4' does not exist.
[  +19 ms] * Try:
[  +17 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 16s
[ +175 ms] Running Gradle task 'assembleDebug'... (completed in 18.9s)
[+1641 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +16 ms] "flutter run" took 23,987ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Environment (please complete the following information):**

 - Android version 5, project  min sdk 19 
 - Version of `barcode_scan` : barcode_scan: ^3.0.1
 - Output of `flutter --version`: 
```
flutter 1.20.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 840c9205b3 (29 hours ago) • 2020-08-04 20:55:12 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```

**Comment by WellsYoo** [comment]
I have the same problem.

**Comment by doanbh** [comment]
Work for me:
https://stackoverflow.com/a/63406002/9405238

**Comment by mshamsi502** [comment]
I have the same problem too.
