### ISSUE TITLE
Not detecting PDF417 barcode on Android. In iOS, PDF417 barcode reading is slow..[Bug]

### ISSUE THREAD

**Issue by bharathiselvan** [mintware-de/flutter_barcode_reader#292]
This package is not reading the PDF417 barcode found in driving licenses on Android. But able to read other formats like Code128, upce etc. In iOS, the PDF417 barcode read rate is slow.

**To Reproduce**
1. Open the example app and read the PDF417 barcode present in driving license

**Expected behavior**
Barcode should be read successfully.

**Logs**
If applicable, add the verbose output of `flutter run`.

**Environment (please complete the following information):**
 - [ ] iOS? Version: ... 13.6.1
 - [ ] Android? Version: ... 9
 - [ ] Real Device? Which?: ... Android - RealMe 5i , iOS 8 plus
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan` -- 3.0.1
 - Output of `flutter --version`: 
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (2 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by bharathiselvan** [comment]
Find the debug logs below.. 

/chatty  (17634): uid=10255(com.example.sample) CameraHandlerTh identical 22 lines
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
I/chatty  (17634): uid=10255(com.example.sample) CameraHandlerTh identical 16 lines
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
I/chatty  (17634): uid=10255(com.example.sample) CameraHandlerTh identical 4 lines
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
I/chatty  (17634): uid=10255(com.example.sample) CameraHandlerTh identical 2 lines
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (17634): Access denied finding property "vendor.camera.aux.packagelist"
E/ZXingScannerView(17634): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/ZXingScannerView(17634): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/ZXingScannerView(17634): 	at android.hardware.Camera.setHasPreviewCallback(Native Method)
E/ZXingScannerView(17634): 	at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:1029)
E/ZXingScannerView(17634): 	at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169)
E/ZXingScannerView(17634): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1350)
E/ZXingScannerView(17634): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/ZXingScannerView(17634): 	at android.os.Looper.loop(Looper.java:226)
E/ZXingScannerView(17634): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/SurfaceView(17634): 9037887 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
I/SurfaceView(17634): 9037887 surfaceChanged -- format=4 w=720 h=1512 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
I/SurfaceView(17634): 163228310 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
