### ISSUE TITLE
Fails to run: `Security exception: Permission Denial: starting Intent`

### ISSUE THREAD

**Issue by haarts** [mintware-de/flutter_barcode_reader#41]
Today I've updated Flutter and a bunch of packages.
`barcode_scan` stopped working after this. When trying to build the project I get:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Finished with error: Exit code 255 from: /home/foo/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true foundation.foo.bar/com.apptreesoftware.barcodescan.BarcodeScannerActivity:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=foundation.foo.bar/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=foundation.foo.bar/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) } from null (pid=4729, uid=2000) not exported from uid 10079

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=foundation.foo.bar/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) } from null (pid=4729, uid=2000) not exported from uid 10079
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1632)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:438)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:278)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:817)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4532)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15014)
	at android.os.Binder.shellCommand(Binder.java:594)
	at android.os.Binder.onTransact(Binder.java:492)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
	at android.os.Binder.execTransact(Binder.java:697)

```

My `AndroidManifest.xml` hasn't changed. I do not have the Kotlin stuff in my `build.gradle` file.
What could cause this? 

Flutter: 0.6.0
barcode_scan: 0.0.6
Dart: 2.1.0-dev

**Comment by matthewtsmith** [comment]
Do you have com.apptreesoftware.barcodescan.BarcodeScannerActivity declared in your AndroidManifest.xml?

**Comment by haarts** [comment]
Yes I do. It worked previously.

**Comment by bhammer88** [comment]
is the uses-permission for the camera there?

**Comment by haarts** [comment]
The permissions are there indeed.
But I've found the culprit! After some twiddling around I stumbled upon this SO post: https://stackoverflow.com/questions/19829507/android-java-lang-securityexception-permission-denial-starting-intent.
Adding `android:exported="true"` to the Activity definition fixed the issue. This should be added to the README I guess.

**Comment by Pushan-Gupta** [comment]
@haarts With android:exported="true" my app just launches the barcode scanner. Then I have to press back button then click on the installed icon again

**Comment by Pushan-Gupta** [comment]
Try

https://github.com/apptreesoftware/flutter_barcode_reader/issues/32#issuecomment-420516729

**Comment by dark-chocolate** [comment]
On running the app from Android Studio (natively), it just runs successfully.

**Comment by Pushan-Gupta** [comment]
@dark-chocolate No, the issue arose when dart sdk was updated recently.

**Comment by dark-chocolate** [comment]
@Pushan-Gupta Did you find any solution?

**Comment by sdabbo** [comment]
I moved the `BarcodeScannerActivity` below the `MainActivity` in the `AndroidManifest.xml`. That fixed the issue for me.
I did not add the exported="true".

**Comment by Pushan-Gupta** [comment]
@dark-chocolate Yes I did. Check my reference above in the comments.

**Comment by dark-chocolate** [comment]
@beatzcraft Thanks a lot. Your solution finally worked. Don't know the insane reason (putting it below the `MainActivity`) but it just worked. Thanks for sharing it. +1

**Comment by alexandrefett** [comment]
Solved for me too. +1

**Comment by arpitcybernetyx** [comment]
1. android:exported="true"
2. 
```
<intent-filter>
        <action android:name="android.intent.action.MAIN" >
        </action>
    </intent-filter>
```

Both are required . 

```
<activity
    android:name="com.example.lib.MainActivity"
    android:label="LibMain" 
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" >
        </action>
    </intent-filter>
</activity>
```
